import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#000000",
        "inverse-on-surface": "#f5f1df",
        "secondary-fixed": "#e3e2df",
        "on-secondary-fixed-variant": "#464744",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1c11",
        "on-secondary-fixed": "#1b1c1a",
        "primary-fixed": "#e5e2e1",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-fixed": "#410003",
        "surface-container-highest": "#e6e3d1",
        "secondary-container": "#e0e0dc",
        "primary-fixed-dim": "#c8c6c5",
        "on-surface-variant": "#444748",
        "secondary-fixed-dim": "#c7c7c3",
        "primary-container": "#1c1b1b",
        "inverse-surface": "#323125",
        "on-secondary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "on-tertiary-container": "#ea4b44",
        "on-surface": "#1c1c11",
        "surface-bright": "#fdfae8",
        "on-error-container": "#93000a",
        "surface-dim": "#dedac9",
        secondary: "#5e5f5c",
        "on-secondary-container": "#626360",
        "inverse-primary": "#c8c6c5",
        "on-error": "#ffffff",
        "outline-variant": "#c4c7c7",
        "on-primary-fixed-variant": "#474746",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary-fixed-variant": "#92030f",
        "on-primary-container": "#858383",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#410003",
        "surface-container-high": "#ece8d7",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#f8f4e2",
        tertiary: "#000000",
        "surface-container": "#f2eedc",
        outline: "#747878",
        surface: "#fdfae8",
        "tertiary-fixed-dim": "#ffb4ac",
        background: "#fdfae8",
        "error-container": "#ffdad6",
        "surface-variant": "#e6e3d1",
      },
      borderRadius: {
        none: "0",
        DEFAULT: "0",
        lg: "0",
        xl: "0",
        full: "0",
      },
      spacing: {
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        "edge-margin": "2rem",
        hairline: "1px",
        "column-gap": "1.5rem",
      },
      fontFamily: {
        "headline-xl": ["Playfair Display", "serif"],
        "body-md": ["'Source Serif 4'", "serif"],
        caption: ["'Source Serif 4'", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-caps": ["Archivo Narrow", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["'Source Serif 4'", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        caption: ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
export default config;
